# Generated by Django 3.1 on 2021-05-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ptt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('new', models.BooleanField()),
                ('sold', models.BooleanField()),
                ('account', models.CharField(max_length=255)),
                ('box', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=255)),
                ('page_number', models.IntegerField()),
            ],
        ),
    ]
