# Generated by Django 3.1 on 2021-06-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landtop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'landtop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ptt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('new', models.IntegerField(blank=True, null=True)),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('box', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ptt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawPtt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('html_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_ptt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PttRawPtt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ptt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone_app.ptt')),
                ('raw_ptt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone_app.rawptt')),
            ],
            options={
                'db_table': 'ptt_raw_ptt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PttLandtop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('landtop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone_app.landtop')),
                ('ptt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone_app.ptt')),
            ],
            options={
                'db_table': 'ptt_landtop',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ptt',
            name='landtop',
            field=models.ManyToManyField(through='smartphone_app.PttLandtop', to='smartphone_app.Landtop'),
        ),
        migrations.AddField(
            model_name='ptt',
            name='raw_ptt',
            field=models.ManyToManyField(through='smartphone_app.PttRawPtt', to='smartphone_app.RawPtt'),
        ),
    ]
