# Generated by Django 3.1 on 2021-05-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0002_auto_20210519_0410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartphoneAppPtt',
        ),
        migrations.AlterModelTable(
            name='ptt',
            table='ptt',
        ),
    ]
