# Generated by Django 3.1 on 2021-05-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0003_auto_20210519_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='PttLandtop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ptt_landtop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SmartphoneAppPtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('new', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('account', models.CharField(max_length=255)),
                ('box', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('page_number', models.IntegerField()),
            ],
            options={
                'db_table': 'smartphone_app_ptt',
                'managed': False,
            },
        ),
    ]
