# Generated by Django 3.1 on 2021-05-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0004_pttlandtop_smartphoneappptt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartphoneAppPtt',
        ),
    ]
