# Generated by Django 3.1 on 2021-05-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0005_delete_smartphoneappptt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptt',
            options={'managed': True},
        ),
    ]
