# Generated by Django 3.1 on 2021-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0006_auto_20210529_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ptt',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptt',
            name='landtop',
            field=models.ManyToManyField(through='smartphone_app.PttLandtop', to='smartphone_app.Landtop'),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='box',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
