# Generated by Django 3.1 on 2021-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0007_auto_20210530_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
