# Generated by Django 3.1 on 2021-06-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone_app', '0008_ptt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PttRawPtt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ptt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone_app.ptt')),
                ('raw_ptt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone_app.rawptt')),
            ],
            options={
                'db_table': 'ptt_raw_ptt',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ptt',
            name='raw_ptt',
            field=models.ManyToManyField(through='smartphone_app.PttRawPtt', to='smartphone_app.RawPtt'),
        ),
    ]
